[project]
name = "mc-bot"
version = "0.1.0"
description = "MC discord bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.1",
    "mcstatus>=11.1.1",
    "py-cord[voice]>=2.6.1",
    "pytz>=2025.2",
]
